
source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!

platform :ios, '9.0'

target 'FYFWebComponent_Example' do
  pod 'FYFWebComponent', :path => '../'

  target 'FYFWebComponent_Tests' do
    inherit! :search_paths

    
  end
end
